const test=require('node:test');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
const {cards,rules,styles,root}=require('./meta-fixtures.cjs');
const modules=Promise.all(['meta-engine','meta-store','combat-rules'].map(name=>import(pathToFileURL(path.join(root,`src/${name}.js`)))));
const deck=['ironclad','ember_archer','archer_tower','boulderback','arc_mage','rambeast','sky_manta','nova_flask'];
test('shared rules preserve exact Aether economy and spell targeting',async()=>{
  const [,,r]=await modules;
  assert.ok(Math.abs(5+r.aetherIncomeBetween(0,180,rules.match)-90.71428571428572)<1e-9);
  assert.ok(Math.abs(5+r.aetherIncomeBetween(0,300,rules.match)-197.85714285714286)<1e-9);
  assert.equal(r.aetherMultiplier(119.9,rules.match),1);assert.equal(r.aetherMultiplier(120,rules.match),2);assert.equal(r.aetherMultiplier(240,rules.match),3);
  assert.equal(r.spellDamageFor(cards.meteor_shards,true),0);assert.equal(r.spellDamageFor(cards.meteor_shards,false),262);assert.equal(r.spellDamageFor(cards.meteor_shards,false,true),40);
  assert.equal(r.canDirectTarget(cards.frost_fang,cards.vampire_bats),false);assert.equal(r.canDirectTarget(cards.vampire_bats,cards.frost_fang),true);assert.equal(r.canDirectTarget(cards.storm_raven,cards.frost_fang),false);assert.equal(r.canDirectTarget(cards.storm_raven,{tower:true}),true);
});
test('shared Frost slow refreshes without stacking and stun refreshes',async()=>{
  const [,,r]=await modules,state={};r.refreshSlow(state,.3,2,5);r.refreshSlow(state,.3,2,6);assert.equal(state.slowPct,.3);assert.equal(state.slowUntil,8);assert.equal(r.movementMultiplier(state,7),.7);assert.equal(r.movementMultiplier(state,8),1);r.refreshStun(state,.4,5);r.refreshStun(state,.4,5.2);assert.equal(state.stunUntil,5.6000000000000005);
});
test('Wilson bounds and Bayesian prior keep raw and adjusted evidence distinct',async()=>{
  const [,,r]=await modules;assert.equal(r.adjustedWinRate(0,0),50);assert.equal(r.adjustedWinRate(1,1),52);assert.deepEqual(r.wilsonInterval(0,0),{low:0,high:100});const ci=r.wilsonInterval(50,100);assert.ok(ci.low<50&&ci.high>50);assert.ok(ci.low>40&&ci.high<60);
});
test('event combat is deterministic for seed including telemetry, AI and outcomes',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});const a=e.simulate(7711,{record:true}),b=e.simulate(7711,{record:true});delete a.milliseconds;delete b.milliseconds;assert.deepEqual(a,b);assert.ok(a.events.some(e=>e.type==='play'));assert.ok(a.events.some(e=>e.type==='damage'));assert.equal(a.events.at(-1).type,'end');
});
test('recorded HP damage exactly reconciles to per-card telemetry',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles}),match=e.simulate(91,{record:true});for(const side of match.sides)for(const [id,row]of Object.entries(side.rows)){const events=match.events.filter(ev=>ev.type==='damage'&&ev.team===side.team&&ev.cardId===id);for(const [kind,metric]of [['troop','troopDamage'],['tower','towerDamage'],['building','buildingDamage']])assert.ok(Math.abs(events.filter(ev=>ev.targetKind===kind).reduce((n,ev)=>n+ev.damage,0)-row[metric])<1e-6);assert.equal(row.aether,row.uses*cards[id].cost);}
});
test('mirror cards contribute pick and telemetry while clean WR excludes them',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});e.ingest(e.simulate(111,{deckA:deck,deckB:deck}));const view=e.view();for(const row of view.cards.filter(r=>deck.includes(r.id))){assert.equal(row.cleanN,0);assert.equal(row.adjustedWinRate,50);assert.equal(row.rawWinRate,null);assert.equal(row.pickRate,100);assert.equal(row.appearances,2);}assert.equal(view.validation.mirrorExclusions,16);assert.equal(view.validation.pickRateTotal,800);assert.ok(view.synergies.every(p=>p.pairGames===0));
});
test('all 14 metrics and special mechanics are finite and event-derived in 200 matches',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(200);const v=e.view();assert.equal(v.cards.length,14);assert.equal(v.synergies.length,91);assert.equal(v.matchups.length,196);assert.equal(v.personalities.length,7);assert.equal(v.archetypes.length,10);for(const row of v.cards){assert.ok(row.cleanN>0);for(const value of Object.values(row))if(typeof value==='number')assert.ok(Number.isFinite(value));assert.ok(row.survivalRate>=0&&row.survivalRate<=100);assert.ok(row.connectionRate>=0&&row.connectionRate<=100);assert.ok(row.slowUptime>=0&&row.slowUptime<=100);assert.ok(row.stunUptime>=0&&row.stunUptime<=100);assert.ok(Math.abs(row.aetherPerGame-row.usesPerGame*cards[row.id].cost)<1e-8);}const frost=v.cards.find(r=>r.id==='frost_fang'),raven=v.cards.find(r=>r.id==='storm_raven'),meteor=v.cards.find(r=>r.id==='meteor_shards'),building=v.cards.find(r=>r.id==='archer_tower');assert.ok(frost.slowUptime>0);assert.ok(raven.auraDamagePerGame>0);assert.ok(raven.unitsStunnedPerGame>0);assert.equal(meteor.towerDamagePerGame,0);assert.equal(meteor.buildingDamagePerGame,0);assert.ok(meteor.initialDamagePerGame>0&&meteor.dotDamagePerGame>0);assert.ok(meteor.dotTicksPerCast<=5+1e-6);assert.ok(building.damagePreventedPerGame>0&&building.pullsPerGame>0);assert.ok(building.lifetimeUtilization<=100+1e-6);assert.ok(v.validation.sanity);
});
test('style and archetype filters have correct 800% eight-card denominator',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(70);for(const style of Object.keys(styles)){const v=e.view({style});assert.ok(v.filteredAppearances>0);assert.ok(Math.abs(v.cards.reduce((n,r)=>n+r.pickRate,0)-800)<1e-7);}for(const archetype of ['Beatdown','Cycle','Control','Hybrid']){const v=e.view({archetype});assert.ok(Math.abs(v.cards.reduce((n,r)=>n+r.pickRate,0)-800)<1e-7);}const v=e.view({style:'control',archetype:'Hybrid'});assert.ok(Math.abs(v.cards.reduce((n,r)=>n+r.pickRate,0)-800)<1e-7);
});
test('empirical pair samples shrink their actual WR delta toward baseline',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(60);const pairs=e.view().synergies;assert.ok(pairs.some(p=>p.pairGames>0));for(const p of pairs.filter(p=>p.pairGames)){assert.ok(Math.abs(p.synergyDelta)<=Math.abs(p.rawDelta)+1e-8);assert.ok(Math.abs(p.pairWinRate-p.expectedBaseline-p.synergyDelta)<1e-7);assert.ok(p.ciLow<=p.ciHigh);}
});
test('mechanical matrix explains Frost air restriction and Raven secondary aura',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});const frost=e.matchup('frost_fang','vampire_bats');assert.ok(frost.advantage<0);assert.ok(frost.reasons.some(r=>r.includes('cannot target air')));const raven=e.matchup('storm_raven','vampire_bats');assert.ok(raven.reasons.some(r=>r.includes('82 damage')));for(const a of Object.keys(cards))for(const b of Object.keys(cards)){const x=e.matchup(a,b),y=e.matchup(b,a);assert.ok(Math.abs(x.advantage+y.advantage)<1e-8);}
});
test('confidence alert engine stays quiet for tiny samples',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(20);assert.equal(e.view().alerts.length,0);
});
test('bad simulations, nonfinite numbers and invalid decks are detected',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});assert.throws(()=>e.simulate(1,{deckA:['ironclad']}));const bad=e.simulate(52);bad.sides[0].rows[bad.sides[0].deck[0]].troopDamage=Infinity;assert.equal(e.ingest(bad),false);assert.equal(e.validation().games,0);assert.equal(e.validation().nanCount,1);const over=e.simulate(91);over.sides[0].spent=10000;assert.equal(e.ingest(over),false);assert.equal(e.validation().invalidSimulations,2);
});
test('restore retains exact aggregates and future stats create a new fingerprint',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(20);const snapshot=e.snapshot(),other=createMetaEngine(cards,{rules,styles,saved:snapshot});assert.deepEqual(other.dataset,snapshot);assert.equal(other.validation().gamesPerMinute,0);other.runBatch(1);assert.ok(other.validation().gamesPerMinute>0);const modified=structuredClone(cards);modified.ironclad.damage++;const changed=createMetaEngine(modified,{rules,styles,saved:snapshot});assert.equal(changed.dataset.games,0);assert.notEqual(changed.identity.fingerprint,e.identity.fingerprint);
});
test('archetype/personality reports obey crossed filters without reusing global samples',async()=>{
  const [{createMetaEngine}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(50);const style=e.view({style:'control'});assert.equal(style.personalities.length,1);assert.equal(style.personalities[0].style,'control');assert.equal(style.archetypes.find(a=>a.name==='Hybrid').n,style.personalities[0].n);const archetype=e.view({archetype:'Hybrid'});assert.equal(archetype.archetypes.length,1);assert.equal(archetype.archetypes[0].name,'Hybrid');assert.equal(archetype.personalities.length,7);assert.match(archetype.historyScope,/whole-dataset/);
});
test('one thousand seeded Cycle drafts always respect the stable 3.375 cost ceiling',async()=>{
  const {createDeckAnalyzer}=await import(pathToFileURL(path.join(root,'src/deck-analysis.js')));const [,,{seededRandom}]=await modules,a=createDeckAnalyzer(cards);for(let seed=1;seed<=1000;seed++){const deck=a.buildAiDeck('cycle',seededRandom(seed)),p=a.analyzeDeck(deck);assert.ok(p.averages.cost<=3.375,`seed ${seed}: ${p.averages.cost}`);assert.equal(new Set(deck).size,8);assert.ok(p.metrics.sustainedAntiAir>=2&&p.counts.winConditions>=1&&p.metrics.cheap>=4);}
});
test('patch store keeps version/stat/model fingerprints separate and blank historical evidence',async()=>{
  const [{createMetaEngine},{createMetaStore}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(5);const s=createMetaStore({cards,rules,styles});assert.equal(s.commit(e.snapshot()),true);assert.equal(s.current().games,5);const versions=s.versions();for(const name of ['V12.8','V12.10','V14'])assert.ok(versions.some(v=>v.version===name&&v.available===false));const comparison=s.compare('unavailable-V14',s.state.activeId);assert.equal(comparison[0].winRateDelta,null);assert.equal(comparison[0].damageDelta,null);s.resetCurrent();assert.equal(s.current(),null);assert.ok(s.versions().some(v=>v.label==='V15 prior run'&&v.games===5));const modified=structuredClone(cards);modified.ironclad.damage++;const changed=createMetaStore({cards:modified,rules,styles,saved:s.serialize()});assert.notEqual(changed.state.activeId,s.state.activeId);assert.ok(changed.versions().some(v=>v.games===5));
});
test('limited V14 old save import exposes only measured old values without cloning patch sessions',async()=>{
  const [,{createMetaStore}]=await modules,s=createMetaStore({cards,rules,styles,legacy:{games:20,cards:{ironclad:{decks:20,nonMirrorGames:10,nonMirrorWins:6,nonMirrorDraws:0,uses:50,aether:150,troopDamage:10000,towerDamage:1000,kills:12,deaths:10}}}});const v=s.view({version:'legacy-v1210-v14'});assert.equal(v.games,20);assert.equal(v.cards[0].pickRate,50);assert.equal(v.cards[0].rawWinRate,60);assert.equal(v.cards[0].usesPerGame,2.5);assert.equal(v.cards[0].damageTakenPerGame,null);assert.equal(v.archetypes.length,0);assert.equal(s.versions().filter(v=>v.available&&v.games===20).length,1);
});
test('future patch comparisons use each card\'s own archetype observations',async()=>{
  const [{createMetaEngine},{createMetaStore},r]=await modules,before=createMetaEngine(cards,{rules,styles});before.runBatch(60);const original=createMetaStore({cards,rules,styles});original.commit(before.snapshot());const changedCards=structuredClone(cards);changedCards.arc_mage.damage++;const after=createMetaEngine(changedCards,{rules,styles,seed:773});after.runBatch(60);const changed=createMetaStore({cards:changedCards,rules,styles,saved:original.serialize()});changed.commit(after.snapshot());const comparisons=changed.compare(original.state.activeId,changed.state.activeId);assert.ok(comparisons.some(c=>c.archetypeChanges.length>0));for(const c of comparisons)for(const delta of c.archetypeChanges){const old=before.dataset.archetypes[delta.name].cards[c.id],next=after.dataset.archetypes[delta.name].cards[c.id];assert.equal(delta.winRateDelta,r.adjustedWinRate(next.score,next.cleanN)-r.adjustedWinRate(old.score,old.cleanN));assert.equal(delta.nBefore,old.cleanN);assert.equal(delta.nAfter,next.cleanN);}
});
test('incompatible event-model archives retain measured card aggregates and original identity',async()=>{
  const [{createMetaEngine},{createMetaStore}]=await modules,e=createMetaEngine(cards,{rules,styles});e.runBatch(100);const s=createMetaStore({cards,rules,styles});s.commit(e.snapshot());const saved=s.serialize(),archived=saved.datasets[0];archived.id='V15-old-model';archived.identity.model='v15-event-1';archived.identity.fingerprint='prior-model-fingerprint';archived.dataset.identity={...archived.identity};const restored=createMetaStore({cards,rules,styles,saved}),v=restored.view({version:archived.id});assert.equal(v.limited,true);assert.equal(v.identity.model,'v15-event-1');assert.equal(v.identity.fingerprint,'prior-model-fingerprint');assert.equal(v.games,100);assert.equal(v.history.length,1);for(const row of v.cards){const stat=e.dataset.cards[row.id];assert.equal(row.cleanN,stat.cleanN);assert.equal(row.pickRate,stat.appearances/200*100);assert.equal(row.rawWinRate,stat.cleanN?stat.score/stat.cleanN*100:null);assert.equal(row.usesPerGame,stat.uses/(stat.appearances||1));assert.equal(row.troopDamagePerGame,stat.troopDamage/(stat.appearances||1));}assert.ok(Math.abs(v.validation.pickRateTotal-800)<1e-7);assert.equal(v.synergies.length,0);const filtered=restored.view({version:archived.id,style:'control'});assert.ok(filtered.filteredAppearances>0&&filtered.filteredAppearances<200);assert.ok(Math.abs(filtered.cards.reduce((n,r)=>n+(r.pickRate||0),0)-800)<1e-7);
});
