const test=require('node:test'),assert=require('node:assert/strict');
const load=()=>import('../src/lab-storage.js');
const payload=name=>({meta:{schema:2,datasets:[{id:name,dataset:{games:32}}]},replays:[{id:name,events:[{time:2,type:'card_play'}]}]});
function memory(){const map=new Map();return{getItem:key=>map.get(key)||null,setItem:(key,value)=>map.set(key,value),removeItem:key=>map.delete(key),map};}
test('lab telemetry survives an origin-independent server round trip',async()=>{const{createLabPersistence}=await load();let disk=null;const fetcher=async(url,options)=>{assert.equal(url,'/api/lab');if(options.method==='POST'){disk=JSON.parse(options.body);return{ok:true};}return{ok:true,json:async()=>disk};};const a=createLabPersistence({storage:memory(),fetcher});await a.save(payload('Unicode 雪'));const b=createLabPersistence({storage:memory(),fetcher});assert.deepEqual((await b.load()).replays,payload('Unicode 雪').replays);assert.equal(disk.schema,1);});
test('failed writes retain pending local telemetry over an older server archive',async()=>{const{createLabPersistence}=await load(),storage=memory();const a=createLabPersistence({storage,fetcher:async()=>({ok:false})});assert.equal(await a.save(payload('new')),false);const b=createLabPersistence({storage,fetcher:async()=>({ok:true,json:async()=>({schema:1,...payload('old')})})});assert.equal((await b.load()).replays[0].id,'new');assert.ok(storage.getItem('rift_crown_lab_pending_v15'));});
test('queued saves preserve order and an older completion cannot clear the newer pending marker',async()=>{const{createLabPersistence}=await load(),storage=memory(),releases=[],names=[];const lab=createLabPersistence({storage,fetcher:(_,options)=>new Promise(resolve=>{names.push(JSON.parse(options.body).replays[0].id);releases.push(()=>resolve({ok:true}));})});const first=lab.save(payload('first'));await Promise.resolve();await Promise.resolve();const second=lab.save(payload('second'));releases.shift()();await first;assert.ok(storage.getItem('rift_crown_lab_pending_v15'));await Promise.resolve();releases.shift()();await second;assert.deepEqual(names,['first','second']);assert.equal(storage.getItem('rift_crown_lab_pending_v15'),null);});
test('malformed archives are ignored and storage quota failures still permit disk saving',async()=>{const{createLabPersistence}=await load();let body;const lab=createLabPersistence({storage:{getItem:()=>'{bad',setItem:()=>{throw Error('quota');},removeItem(){}},fetcher:async(_,options)=>{body=options.body;return{ok:true,json:async()=>({schema:1,meta:{schema:0},replays:[]})};}});assert.equal(await lab.load(),null);assert.equal(await lab.save(payload('disk')),true);assert.equal(JSON.parse(body).replays[0].id,'disk');});
test('early wrapped replay saves migrate without discarding Meta history',async()=>{const{createLabPersistence}=await load();const archive={schema:1,meta:payload('archive').meta,replays:{formatVersion:1,replays:payload('archive').replays}};const lab=createLabPersistence({storage:memory(),fetcher:async()=>({ok:true,json:async()=>archive})});const loaded=await lab.load();assert.deepEqual(loaded.replays,payload('archive').replays);assert.equal(loaded.meta.datasets[0].dataset.games,32);});
test('actual game persistLabSave uses recorder output that survives reload hydration',async()=>{const{createLabPersistence}=await load(),{createBattleRecorder}=await import('../src/battle-recorder.js'),{createMetaStore}=await import('../src/meta-store.js'),{createMetaEngine}=await import('../src/meta-engine.js');const{cards,rules,styles}=require('./meta-fixtures.cjs'),{makeContext,install}=require('./v14-harness.cjs'),storage=memory();let disk=null;const fetcher=async(_,options)=>{if(options.method==='POST'){disk=JSON.parse(options.body);return{ok:true};}return{ok:true,json:async()=>disk};};const engine=createMetaEngine(cards,{rules,styles});engine.runBatch(4);const store=createMetaStore({cards,rules,styles});store.commit(engine.snapshot());const recorder=createBattleRecorder(cards,{storage:null});recorder.start({aiStyle:'control'});recorder.event(1,'card_play',{team:'player',cardId:'ironclad',cost:3});recorder.finish(2,{winner:'player'});const c=makeContext();c.labPersistence=createLabPersistence({storage,fetcher});c.game.metaLab={serialize:()=>store.serialize()};c.game.recorder=recorder;c.game.running=false;install(c,['persistLabSave']);assert.equal(await c.persistLabSave(),true);assert.ok(Array.isArray(disk.replays));const loaded=await createLabPersistence({storage:memory(),fetcher}).load();assert.equal(loaded.meta.datasets[0].dataset.games,4);const next=createBattleRecorder(cards,{storage:null});next.hydrate(loaded.replays);assert.equal(next.history().length,1);assert.equal(next.history()[0].duration,2);});
